version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGurl_db: url_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      target: backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: url_db
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/root/uploads

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    environment:
      API_BASE: http://localhost:8080/api
    depends_on:
      - backend

volumes:
  postgres_data: 